### ISSUE TITLE
[BUG] Server errors out on responses with body size greater than 32M

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#256]
**Describe the bug**
Some endpoints are expected to keep growing in response size following platform usage. These endpoints will most probably return responses with more than 32M of size (as has happened with the results for the FeTS Challenge), which gets blocked by GCP, raising a 500 Internal Error.

**To Reproduce**
1. Run a medperf instance through GCP
2. Post multiple objects of the same type (datasets for example), where in total, the contents of all entities goes beyond 32M in size
3. get all previously generated entities with the bulk get endpoint (GET /datasets/ for example).
4. The server will fail and return 500 Internal Error

**Expected behavior**
The server should either allow for larger responses, or provide tools to reduce the size of the response through something like pagination. In cases where the size surpasses 32M, a meaningful error description should be provided to the user.

**Screenshots**
<img width="1375" alt="Screen Shot 2022-09-19 at 12 54 16 PM" src="https://user-images.githubusercontent.com/26156883/191082157-c46a8f96-7cce-4695-8eb7-7233633732b7.png">
Failed GET request because the FeTS Challenge has over 730 results, each of which is large by itself.

**Tasks**

- [ ] #294
- [x] #295

**Comment by msheller** [comment]
Johnu makes a good point that pagination can depend on the UI, such that you make calls only for what the UI will show.

To this end, the UI should have a configuration/interface for the client code to retrieve how many rows the UI wants. For the CLI, this can default to infinite, since presumably the output goes to stdout or a file (i.e. you're piping it to something).

**Comment by msheller** [comment]
Johnu points out that the server cannot detect this error, since it happens at the GCP layer, so the error code cannot be specific. There can be cases where we get 500 for other reasons, so the back-off approach should start at something reasonable to prevent a crapload of failures in a row due to the 500 being for a different reason.

So we decided on the number 32 for the CLI :) This number is chosen fairly arbitrarily.
