### ISSUE TITLE
[BUG] MLCube assets are not updated after content or url change

### ISSUE THREAD

**Issue by aristizabal95** [mlcommons/medperf#549]
**Describe the bug**
MLCubes are constructed from multiple assets, all of which are downloaded the first time such MLCube is requested by the CLI. After subsequent requests to the MLCube, cached assets are preferred. This is okay as long as the contents of the remote MLCube don't change. But, if assets are updated, contents are modified or the hash changes, while the MLCube metadata gets updated, assets are not redownloaded, or rechecked with the new hash. This leads to people running outdated MLCubes without knowledge, and can also lead to broken MLCube registration updates, because tests on the user side will pass due to local cache being valid instead of remote contents being revised.

**To Reproduce**
1. Submit an MLCube and run it
2. Change the URL of one of the assets (MLCube URL for example) to something nonsensical through the admin dashboard
3. Run the MLCube again. It runs as usual
4. Change the hash of one of the assets (parameters hash for example) to something nonsensical through the admin dashboard
5. Run the MLCube again. It still runs like normal
6. Remove mepderf's cache of that MLCube
7. Run the MLCube again. It now fails.

**Expected behavior**
When the asset url or hash changes, the local cache should be invalidated or removed before proceeding with the download.

**Additional context**
This raises a question. We can detect asset change by hash change or url change. What happens when the contents of the asset change, but not the url? We cannot detect content changes without downloading the asset again. Someone could submit an MLCube with, for example, a url for the latest mlcube.yaml in a repository. In that case, contents may change, but the link is the same. Users that have downloaded that MLCube previously will not have any issues later on because local cache is used for that asset, but new users of that MLCube will encounter issues because of hash mismatch. How can we proceed here? Should we prefer redownloading lightweight assets like yaml files? What about heavy assets like additional files?

**Comment by draviren** [comment]
should the url include the hash, e.g. as a parameter? when updated, that parameter may cause the url to give error ...

**Comment by hasan7n** [comment]
https://github.com/mlcommons/medperf/blob/001bd9f707263311557939d360f8007cffe247fe/cli/medperf/comms/entity_resources/resources.py#L36-L37

The problem seems to stem from the logic above. Note that we have this logic in each function in this `recources.py` file. We are checking that if the asset already exists in the filesystem, we just return. We don't verify its hash.
The logic should be modified to add a hash verification, and accordingly return if the hash matches, or proceed to download if the hash is mismatched.

I remember we have this current implementation because we were thinking that we are assuming users will not manipulate local assets and hence there is no need to check the hash. But at that time we didn't have the scenario of modifying MLCubes in mind (we were always working with operational MLCubes).

Note that one challenge remains (which is actually what encouraged us to have the current implementation): how to verify the hash of assets like `additional_files`? we only keep track of the compressed tarball hash, not the extracted version.

**Comment by hasan7n** [comment]
> This raises a question. We can detect asset change by hash change or url change. What happens when the contents of the asset change, but not the url? We cannot detect content changes without downloading the asset again. Someone could submit an MLCube with, for example, a url for the latest mlcube.yaml in a repository. In that case, contents may change, but the link is the same. Users that have downloaded that MLCube previously will not have any issues later on because local cache is used for that asset, but new users of that MLCube will encounter issues because of hash mismatch. How can we proceed here? Should we prefer redownloading lightweight assets like yaml files? What about heavy assets like additional files?
@aristizabal95 If I understood your concern correctly, we should be good if we verify the hash as described in my previous comments. We shouldn't care about the remote contents as long as the local cache contents are still compliant with the hash, right?
